.github/workflows/build-doc.yml
.github/workflows/c-cpp.yml
CONTRIBUTING.md
Performance.md
README.md
examples/analytical_apps/pagerank/pagerank.h
examples/analytical_apps/pagerank/pagerank_parallel.h
examples/analytical_apps/pagerank/pagerank_parallel_context.h
examples/analytical_apps/run_app.h
examples/analytical_apps/timer.h
misc/app_tests.sh
misc/doc-config

- Implemented a new version of PageRank which has better performance and is verified on LDBC.
- Updated performance evaluation results for PageRank.
- Minor changes on readme and CI.

Implemented PageRank based on BatchWorker, verified on LDBC.

---

grape/worker/comm_spec.h

Fix: buffer overflow when the length of hostname more than 32 chars

---

examples/analytical_apps/run_app.cc

[MINOR] grape added as prefix of glags

---

examples/analytical_apps/run_app.h
examples/gnn_sampler/append_only_edgecut_fragment.h
grape/fragment/basic_fragment_loader.h
grape/fragment/e_fragment_loader.h
grape/fragment/loader.h
misc/app_tests.sh

https://github.com/alibaba/libgrape-lite/issues/20

[FEATURE-20] Add EFragmentLoader to load graph without vertex file

---

.github/workflows/c-cpp.yml
misc/cpplint.py

Taking it from https://github.com/cpplint/cpplint to fix python3 compatibility.
Looks like that master branch will fail to pass CI in the latest github action worker settings: https://github.com/sighingnow/libgrape-lite/runs/2162751075?check_suite_focus=true
Fixes a bug in cmake by installing the latest version for MacOS as well as a workaround for https://gitlab.kitware.com/cmake/cmake/-/issues/21955
N/A

Upgrade the cpplint script to fix issues for Python 3.

---

grape/utils/atomic_ops.h

add atomic_sub to atomic ops

---

grape/fragment/e_fragment_loader.h

Fixed the compilation errors when loading graph with VDATA_T != EmptyType.

---

grape/communication/sync_comm.h

Fixes bug in AllToAll function when initializing worker_num.

fix_bug_alltoall

---

CMakeLists.txt

Correctly install headers of flat_hash_map

---

grape/worker/comm_spec.h

Providing several getter methods in comm_spec to support querying the host info.
Fixes #50

[FEATURE #50]add host info getters

---

ldbc_driver/pom.xml

Seems the original website has been migrated.
Fixes the CI failures on main.

Fixes the mvn repository for ldbc graphalytics.

---

Performance.md

This reverts commit f91e275368da5cc410aec56d6ef9c84055c8b211.
The link was wrong
Fixes

Revert "Update Performance.md (#84)"

---

grape/graph/adj_list.h
grape/graph/edge.h
grape/graph/vertex.h

fix DEV_HOST macro

---

examples/analytical_apps/cuda/wcc/wcc_opt.h
misc/cuda_app_tests.sh

- fix wcc_opt wrong answer in hash partition
- add this case into cuda_app_test.sh
Fixes

[Bug] fix cuda_app:wcc_opt bugs in hash partition

---

Performance.md

[Typo] fix typo in performance.md

---

grape/graph/id_indexer.h
grape/vertex_map/global_vertex_map.h

[BugFix] Fix the gid return from  AddVertex and add a rvalue-reference AddVertex api to avoid copy oid

---

CMakeLists.txt
README.md

+ Throw a warning if `.git` in submodules directories don't exist
+ Update readme for how to ensure the building of GPU targets
Resolves #107.

Raising a warning message in CMakeLists.txt and update the readme for GPU support.

---

grape/cuda/fragment/host_fragment.h

#92 breaks the GPU graph loader, and this pr should fix it.
Fixes #109

Revise GPU graph loader on undirected graphs.

---

Performance.md
README.md

Introduce GPU feature in README

---

examples/analytical_apps/cdlp/cdlp_context.h

Fixed cdlp failed with GID_AS_LABEL compile option

---

grape/worker/worker.h

[Promotheus Monitor] Print the running time of each round (PEval & IncEval)
The sum of time of each round is 0.001s less than the `run algorithm` time on average.

Print the running time for each round (PEval & IncEval)

---

grape/parallel/parallel_message_manager.h

Add `SendToFragment` for parallel message manager

---

CMakeLists.txt
examples/analytical_apps/wcc/wcc.h
examples/analytical_apps/wcc/wcc_context.h

Default to use OID as component id in WCC algorithm

---

examples/analytical_apps/sssp/sssp.h
examples/analytical_apps/wcc/wcc.h
grape/utils/vertex_array.h

Fixes: The begin value of vertex range in graphscope project fragmet is not always 0

---

.gitignore
examples/analytical_apps/cdlp/cdlp_utils.h

Fixes the CDLP algorithm for std::string OIDs.

---

.github/workflows/build-doc.yml
.github/workflows/c-cpp.yml
examples/gnn_sampler/kafka_producer.h
misc/eps_check.cc

Fix a bug where producer->flush() is only called once in KafkaProducer

---

grape/vertex_map/local_vertex_map.h
grape/vertex_map/vertex_map_base.h
misc/app_tests.sh
tests/vertex_map_tests.cc

When running the test of vertex map, I encountered a small problem with the script, see
Besides, some small code optimization of vertex map is submitted.
Fixes

Small fix of vertex map

---

.gitmodules
CMakeLists.txt
README.md
grape/config.h
grape/cuda/fragment/host_fragment.h
grape/cuda/parallel/parallel_engine.h
grape/cuda/utils/array_view.h
grape/cuda/utils/cuda_utils.h
grape/cuda/utils/shared_array.h
grape/cuda/utils/shared_value.h
grape/cuda/utils/sorted_search.h
grape/cuda/utils/vertex_array.h
grape/cuda/utils/work_source.h
grape/cuda/vertex_map/device_vertex_map.h
grape/utils/concurrent_queue.h

Now `git submodule update --init --recursive` is no longer required.

Remove all the submodules introduced by GPU features.

---

grape/utils/bitset.h

FIX: Fix a bug in bitset.h
