CMakeLists.txt, examples/gnn_sampler/append_only_edgecut_fragment.h, examples/gnn_sampler/kafka_consumer.h, examples/gnn_sampler/kafka_producer.h, grape/utils/gcontainer.h
This pr fixes the memory corruption in gnn_sampler (specifically, in `KafkaConsumer`), where a `delete` should be used, rather than a `free()`.
This pr also:
+ Enhance the kafka part with an extra `delete conf;` to release the memory resource that won't be used anymore
+ Fixed a potential heap-buffer-overflow bug in `GArray`'s resize, when the new size is smaller than the old size.
+ Fixed a bug `append_only_edgecut_fragment.h`, which leads to the `extra_oe_` being copied every time we extend the fragment.
+ Enhance the support for lower version of CMake (i.e., cmake < 3.6) where the `list(FILTER) syntax` is invalid.
=> [BUGFIX] Fix memory corruption bug and a potential buffer-overflow bug.

grape/fragment/basic_fragment_loader.h
Fixed the compilation errors when instantiating fragments with VDATA_T!=EmptyType.
Fixes #11
=> [BUGFIX] Failed to instantiate fragments with VDATA_T!=EmptyType.

examples/analytical_apps/pagerank/pagerank.h
Fix infinite iterations in pagerank algo when max_round <= 0
Fixes #15
=> [BUGFIX-15] Fix infinite iterations in pagerank when max_round<=0

libgrapelite-config.in.cmake
rather than the hard absolute path where it placed during installation.
=> The LIBGRAPELITE_HOME should be pointed to where it locates.

grape/vertex_map/global_vertex_map.h, grape/vertex_map/vertex_map_base.h
add a method to init global vertex map with fnum to  support GraphScope DynamicFragmentVertexMap load duplicated (whole) graph in every worker.
https://github.com/alibaba/GraphScope/issues/317
Fixes
https://github.com/alibaba/GraphScope/pull/325
=> Add a method to init global vertex map with fnum

thirdparty/flat_hash_map/flat_hash_map.hpp
I found under certain compilers, like NVCC, when compiling libgrape-lite using that, the following warning will be reported.
```
/tmp/tmp.oOqUdB4akj/thirdparty/libgrape-lite/thirdparty/flat_hash_map/flat_hash_map.hpp(877): warning: "ska::detailv3::sherwood_v3_table<T, FindKey, ArgumentHash, Hasher, ArgumentEqual, Equal, ArgumentAlloc, EntryAlloc>::templated_iterator<ValueType>::operator ska::detailv3::sherwood_v3_table<std::pair<int64_t, grape::fid_t>, int64_t, std::hash<long>, ska::detailv3::KeyOrValueHasher<int64_t, std::pair<int64_t, grape::fid_t>, std::hash<long>>, std::equal_to<int64_t>, ska::detailv3::KeyOrValueEquality<int64_t, std::pair<int64_t, grape::fid_t>, std::equal_to<int64_t>>, std::allocator<std::pair<int64_t, grape::fid_t>>, …
```
=> Fix warning in flat_hash_map under certain compilers

grape/io/line_parser_base.h, grape/io/tsv_line_parser.h
The current implementation does not eat the new line character - `\n`, so if there's a line `123\n`, the variable `std::string r` will contain a '\n'.
=> Fix string parser bug

Performance.md, README.md, examples/analytical_apps/bfs/bfs.h, examples/analytical_apps/run_app.h, examples/analytical_apps/sssp/sssp.h, examples/analytical_apps/wcc/wcc.h, grape/parallel/parallel_engine.h, grape/parallel/parallel_engine_spec.h, grape/utils/bitset.h, grape/utils/thread_pool.h, grape/utils/vertex_set.h
1. add a ThreadPool class member to ParallelEngine for support of thread reuse in ForEach functions.
2. delivery the ThreadPool to BitSet for support of parallel functions which are previously implemented with openmp.
The experiments were conducted on 4 instances of [r6e.8xlarge] on [AlibabaCloud ECS], each with 32 threads. All the results are averages of 10 runs.
|Algorithm	 |Dataset    	    |Baseline	|Thread Pool	|Improvements|
|------------|------------------|-----------|---------------|------------|
|    SSSP   	 |datagen-9_0-fb 	|0.622	    |0.588	    |6%|
|           	 |datagen-9_1-fb 	|0.765	    |0.765	    |0%|
|           	 |datagen-9_2-zf 	|1.707	    |1.587	    |8%|
|    WCC    	 |datagen-9_0-fb 	|0.764	    |0.725	    |5%|
|           	 |datagen-9_1-fb 	|0.903	    |0.883	    |2%| …
=> Add thread pool and use in ParallelEngine & Bitset

grape/fragment/immutable_edgecut_fragment.h
=> Fix compilation failure under high version gcc(>=10) with -Werror options

.github/workflows/cuda.yml
Disable the cuda CI to ensure our master branch keeps green.
=> Disable the cuda runner as we don't have a self-hosted runner currently.

CMakeLists.txt
Install the third_party `string_view.h` for dependency ([this line](https://github.com/alibaba/libgrape-lite/blob/5809f7612e95d90dfd135318f8507a5367b62fe8/grape/types.h#L23)).
=> [Fix bug] Install third_party dependency string_view.h

grape/fragment/fragment_base.h
=> Fix compile failure under gcc5.4 by adding default constructor to FragmentBase

grape/graph/adj_list.h, grape/graph/edge.h, grape/graph/vertex.h
- Add move constructor to `Vertex`, `Edge` and `Nbr`;
- Mark these ctors with `noexcept` to avoid copy when vector of these structures grows. This is for complex data structure.
Fixes
=> Add move constructor to `Vertex`,  `Edge` and `Nbr`

examples/analytical_apps/pagerank/pagerank_local.h, grape/parallel/auto_parallel_message_manager.h
Test wcc_auto failed in graphscope  with `uint64_t` vid_t
Fixes https://github.com/alibaba/GraphScope/issues/1640
=> Support uint64 type in parallelMessage

grape/graph/de_mutable_csr.h
Add interfaces in DeMutableCSR:
(1) basic methods: `clear`, `find`, and `binary_find`
(2) break the operation of `add_edges` into 3 steps:
(2.1) `reserve_edges` for reserving space (capacity) of edges
(2.2) `put_edge` for inserting an edge, which can be parallel
(2.3) `sort_neighbors` for cleanning up the nerghbors
Fixes
=> Add interfaces following MutableCSR

grape/fragment/partitioner.h, grape/types.h
As titled.
REF:
- https://github.com/alibaba/libgrape-lite/blob/master/thirdparty/string_view/string_view.hpp#L1068
- https://en.cppreference.com/w/cpp/string/basic_string_view
=> [Fix bug] Fix the 'const class std::basic_string_view<char>' has no member named 'to_string' error in C++17.

grape/graph/adj_list.h
Compiling under g++ 12.2.0 raise an warning about dangling pointer
```
/root/libgrape-lite/grape/graph/adj_list.h:266:29: error: storing the address of local variable '<anonymous>' in '*<return-value>.grape::FilterAdjList<unsigned int, grape::E
mptyType, std::function<bool(const grape::Nbr<unsigned int, grape::EmptyType>&)> >::pred_' [-Werror=dangling-pointer=]
266 |       : begin_(b), end_(e), pred_(pred) {
|                             ^~~~~~~~~~~
/root/libgrape-lite/grape/fragment/mutable_edgecut_fragment.h: In member function 'grape::MutableEdgecutFragment<OID_T, VID_T, VDATA_T, EDATA_T, _load_strategy, VERTEX_MAP_T
>::fragment_adj_list_t grape::MutableEdgecutFragment<OID_T, VID_T, VDATA_T, EDATA_T, _load_strategy, VERTEX_MAP_T>::GetIncomingAdjList(const vertex_t&, grape::fid_t) [with …
```
=> Fix dangling pointer warning under g++ 12.2.0

grape/communication/shuffle.h, grape/graph/id_indexer.h, grape/serialization/in_archive.h, grape/serialization/out_archive.h, grape/types.h, grape/utils/string_view_vector.h
as titled, avoiding the conflicts in GraphScope.
N/A
=> Configure the selection of string-view to match with apache-arrow.

CMakeLists.txt
It is useful when we just want to install libgrape-lite as deps, e.g., in vineyard and graphscope.
=> Add a cmake option to opt-out test cases from ALL.

grape/parallel/thread_local_message_buffer.h
Fix [issue](https://github.com/alibaba/GraphScope/issues/2664)
Call flushLocalBuffer() to avoid send big msg between workers, or msg's size(size_t) may over data len's type int in MPI_Isend()
=> Fix overflow of MPI_Isend()'s data size

grape/utils/vertex_array.h
Related issue in GraphScope: https://github.com/alibaba/GraphScope/discussions/2735
=> Correct the operator++(int) and operator--(int) behavior in VertexRange class

grape/utils/bitset.h
The resize function of `Bitset` generates memory error.
=> Fix resize bug and add move constructor for Bitset

examples/analytical_apps/cdlp/cdlp_opt.h
otherwise it could not be compiled with arrow projected fragment
=> Use getter method of nbr to be consistent of projected fragment

CMakeLists.txt
When `run_app` and `run_sampler` been deleted, we hope the `find_package(libgrape-lite)` in CMakeLists.txt still succeed.
=> Don't export bins when install libgrape-lite in CMakeLists.txt

grape/utils/bitset.h
A move ctor was added to `Bitset` since #149, since then, it was no longer trivial-copy-constructible.
When using it in contexts like
```
std::vector<grape::DenseVertexSet<typename FRAG_T::inner_vertices_t> > curr_inner_updated, next_inner_updated;
auto v_label_num = valid_vertexes.size();
curr_inner_updated.resize(v_label_num);
next_inner_updated.resize(v_label_num);
```
it fails to compile under GCC-11.
=> Fixes the missing of copy ctor for bitset

grape/utils/bitset.h
In PR #154 and #149, copy and move ctor for Bitset are added, however, the assignment operator is not added, and there will be compile error, see follow.
=> Fix missing assignment operator for Bitset

grape/utils/bitset.h
The Bitset can be constructed with size == 0, and when another Bitset copies from the empty Bitset, there will be core dump as the memcpy()
=> Fix Bitset's core dump when copying from an empty Bitset

grape/parallel/thread_local_message_buffer.h, grape/util.h, grape/utils/message_buffer_pool.h
Errors were encountered during the building with GraphScope Flex with latest libgrape-lite.
=> Add necessary headers and make `get_available_memory` inline

examples/analytical_apps/bc/staged_bc_bfs.h, examples/analytical_apps/core_decomposition/core_decomposition.h, examples/analytical_apps/kcore/kcore.h, examples/analytical_apps/kcore/kcore_context.h, grape/cuda/utils/cuda_utils.h, grape/cuda/utils/work_source.h, grape/parallel/thread_local_message_buffer_opt.h, grape/types.h, grape/utils/concurrent_queue.h, grape/utils/thread_pool.h, grape/worker/worker.h
1. fix `std::result_of` is deprecated in c++ 17 https://en.cppreference.com/w/cpp/types/result_of
2. fix unused variables.
=> fix: Fix warnings of C++ 17 compiler
